### ISSUE TITLE
lis2mdl_hard_iron

### ISSUE THREAD

**Issue by loveshipting** [STMicroelectronics/lis2mdl#1]
### Device part numbers
lis2mdl
### Question
Hi, I am follow the demo of lis2mdl_hard_iron in the file "lis2mdl_hard_iron.c" to set mag offset, when I read the REG"LIS2MDL_OFFSET_X_REG_L" back, can't get the the value that I set, also the offset of setting not workig. Below is the part of my code, can I have your advice? Thanks.
```
   int16_t mag_offset[3] = {
        0xF500, // OFFSET_X_REG 
        0xF800, // OFFSET_Y_REG
        0xF400, // OFFSET_Z_REG 
    };
    /* Restore default configuration */
    lis2mdl_reset_set(&mag_ctx, PROPERTY_ENABLE);
    do
    {
        lis2mdl_reset_get(&mag_ctx, &rslt);
    } while (rslt);

    /* Enable Block Data Update */
    lis2mdl_block_data_update_set(&mag_ctx, PROPERTY_ENABLE);
    /* Set Output Data Rate to 10 Hz */
    lis2mdl_data_rate_set(&mag_ctx, LIS2MDL_ODR_10Hz);
    /* Set / Reset sensor mode */
    lis2mdl_set_rst_mode_set(&mag_ctx, LIS2MDL_SENS_OFF_CANC_EVERY_ODR);
    /* Enable temperature compensation */
    lis2mdl_offset_temp_comp_set(&mag_ctx, PROPERTY_ENABLE);
    /* Set device in continuous mode */
    lis2mdl_operating_mode_set(&mag_ctx, LIS2MDL_CONTINUOUS_MODE);
    /* Configure Mag offset and enable cancellation   */
    lis2mdl_mag_user_offset_set(&mag_ctx, mag_offset);

    int16_t temp[3];
    rslt |= lis2mdl_mag_user_offset_get(&mag_ctx, temp);
    APP_ERROR_CHECK(rslt);
    NRF_LOG_INFO("temp:%d,%d,%d\r\n", temp[0], temp[1], temp[2]);
```

**Comment by avisconti** [comment]
Fixed by f55528ef3db55df204b8f6a57beee638a5776a5e

**Comment by avisconti** [comment]
@loveshipting 
Can you use this latest version and re-try?  If it doesn't solve your issue, pls re-open it.
Thanks!

**Comment by loveshipting** [comment]
Thanks. I will try it later.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "STMicroelectronics/lis2mdl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月9日(星期四) 下午3:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [STMicroelectronics/lis2mdl] lis2mdl_hard_iron (#1)





 
@loveshipting
 Can you use this latest version and re-try?  If it doesn't solve your issue, pls re-open it.
 Thanks!
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by loveshipting** [comment]
> @loveshipting
> Can you use this latest version and re-try? If it doesn't solve your issue, pls re-open it.
> Thanks!

Hi,
 I found the func "lis2mdl_mag_user_offset_set(&dev_ctx, mag_offset);" still have issue, because I can read the result that I wrote. Then, I found the func
```
 static int32_t lsm6dso_write_lis2mdl_cx(void *ctx, uint8_t reg,
                                        uint8_t *data,
                                        uint16_t len)
{
  axis3bit16_t data_raw_acceleration;
  int32_t ret;
  uint8_t drdy;
  lsm6dso_status_master_t master_status;
  lsm6dso_sh_cfg_write_t sh_cfg_write;
  /* Configure Sensor Hub to read LIS2MDL. */
  sh_cfg_write.slv0_add = (LIS2MDL_I2C_ADD & 0xFEU) >>
                          1; /* 7bit I2C address */
  sh_cfg_write.slv0_subadd = reg,
  sh_cfg_write.slv0_data = *data,
  ret = lsm6dso_sh_cfg_write(&ag_ctx, &sh_cfg_write);
  /* Disable accelerometer. */
  lsm6dso_xl_data_rate_set(&ag_ctx, LSM6DSO_XL_ODR_OFF);
  /* Enable I2C Master. */
  lsm6dso_sh_master_set(&ag_ctx, PROPERTY_ENABLE);
  /* Enable accelerometer to trigger Sensor Hub operation. */
  lsm6dso_xl_data_rate_set(&ag_ctx, LSM6DSO_XL_ODR_104Hz);
  /* Wait Sensor Hub operation flag set. */
  lsm6dso_acceleration_raw_get(&ag_ctx, data_raw_acceleration.i16bit);

  do {
    HAL_Delay(20);
    lsm6dso_xl_flag_data_ready_get(&ag_ctx, &drdy);
  } while (!drdy);

  do {
    HAL_Delay(20);
    lsm6dso_sh_status_get(&ag_ctx, &master_status);
  } while (!master_status.sens_hub_endop);

  /* Disable I2C master and XL (trigger). */
  lsm6dso_sh_master_set(&ag_ctx, PROPERTY_DISABLE);
  lsm6dso_xl_data_rate_set(&ag_ctx, LSM6DSO_XL_ODR_OFF);
  return ret;
}
```
in the file "lsm6dso_sensor_hub_lis2mdl.c", it doest use the param "len".

**Comment by avisconti** [comment]
> > @loveshipting
> > Can you use this latest version and re-try? If it doesn't solve your issue, pls re-open it.
> > Thanks!
> 
> Hi,
> I found the func "lis2mdl_mag_user_offset_set(&dev_ctx, mag_offset);" still have issue, because I can't read the result that I wrote. Then, I found the func
> 
> ```
>  static int32_t lsm6dso_write_lis2mdl_cx(void *ctx, uint8_t reg,
>                                         uint8_t *data,
>                                         uint16_t len)
> {
>   axis3bit16_t data_raw_acceleration;
>   int32_t ret;
>   uint8_t drdy;
>   lsm6dso_status_master_t master_status;
>   lsm6dso_sh_cfg_write_t sh_cfg_write;
>   /* Configure Sensor Hub to read LIS2MDL. */
>   sh_cfg_write.slv0_add = (LIS2MDL_I2C_ADD & 0xFEU) >>
>                           1; /* 7bit I2C address */
>   sh_cfg_write.slv0_subadd = reg,
>   sh_cfg_write.slv0_data = *data,
>   ret = lsm6dso_sh_cfg_write(&ag_ctx, &sh_cfg_write);
>   /* Disable accelerometer. */
>   lsm6dso_xl_data_rate_set(&ag_ctx, LSM6DSO_XL_ODR_OFF);
>   /* Enable I2C Master. */
>   lsm6dso_sh_master_set(&ag_ctx, PROPERTY_ENABLE);
>   /* Enable accelerometer to trigger Sensor Hub operation. */
>   lsm6dso_xl_data_rate_set(&ag_ctx, LSM6DSO_XL_ODR_104Hz);
>   /* Wait Sensor Hub operation flag set. */
>   lsm6dso_acceleration_raw_get(&ag_ctx, data_raw_acceleration.i16bit);
> 
>   do {
>     HAL_Delay(20);
>     lsm6dso_xl_flag_data_ready_get(&ag_ctx, &drdy);
>   } while (!drdy);
> 
>   do {
>     HAL_Delay(20);
>     lsm6dso_sh_status_get(&ag_ctx, &master_status);
>   } while (!master_status.sens_hub_endop);
> 
>   /* Disable I2C master and XL (trigger). */
>   lsm6dso_sh_master_set(&ag_ctx, PROPERTY_DISABLE);
>   lsm6dso_xl_data_rate_set(&ag_ctx, LSM6DSO_XL_ODR_OFF);
>   return ret;
> }
> ```
> 
> in the file "lsm6dso_sensor_hub_lis2mdl.c", it doesn't use the param "len".

But this is a totally different driver/example, which is lsm6dso. It doesn't have to do anything with lis2mdl driver, because the lis2mdl device is attached to the lsm6dso sensor hub, and it uses functions of lsm6dso.

So, if there are issue in lsm6dso examples can you open a proper issue there?

Now, coming back to the original issue, you said that this code:

```
    /* Configure Mag offset and enable cancellation   */
    lis2mdl_mag_user_offset_set(&mag_ctx, mag_offset);

    int16_t temp[3];
    rslt |= lis2mdl_mag_user_offset_get(&mag_ctx, temp);
    APP_ERROR_CHECK(rslt);
    NRF_LOG_INFO("temp:%d,%d,%d\r\n", temp[0], temp[1], temp[2]);
```

is NOT returning same value as the written one. Can you give more details here on what you write and what you read?
Thanks.

**Comment by loveshipting** [comment]
I was use lsm6dso sensor hub to operate lis2mdl, and of course it was lsm6dso issue. I will open issue to lsm6dso. Thanks.

**Comment by avisconti** [comment]
> I was use lsm6dso sensor hub to operate lis2mdl, and of course it was lsm6dso issue. I will open issue to lsm6dso. Thanks.

Sure. 
But what about the lis2mdl_mag_user_offset_set() ?
Did you test it using the lis2mdl_hard_iron.c example?

**Comment by avisconti** [comment]
closing this issue.
re-open it if bug is still there (should not)
